name: example
description: drift_model_generator example. 
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  drift: ^2.3.0
  drift_model_generator:
    path: ../

dev_dependencies:
  drift_dev: ^2.3.3
  build_runner: ^2.3.2
