name: drift_model_generator
description: Dart model based drift model generator.
version: 0.7.0
homepage: https://github.com/skyfet/drift_model_generator

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  drift: ">2.0.0 <3.0.0"
  build: ^2.4.1
  analyzer: ^6.4.1
  source_gen: ^1.5.0

dev_dependencies:
  lints: any