name: drift_model_generator
description: Dart model based drift model generator.
version: 0.5.3
homepage: https://github.com/skyfet/drift_model_generator

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  build: ^2.3.1
  analyzer: ^5.0.0
  source_gen: ^1.2.3

dev_dependencies:
  lints: any