name: drift_model_generator
description: Dart model based drift model generator.
version: 0.1.0
homepage: https://github.com/skyfet/drift_model_generator

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  build: ^2.3.1
  analyzer: ^5.3.1
  source_gen: ^1.2.6

dev_dependencies:
  lints: any