name: drift_model_generator
description: Dart model based drift model generator.
version: 0.0.1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  build: any
  analyzer: any
  source_gen: any

dev_dependencies:
  lints: any